### ISSUE TITLE
Adicionar colaborador

### ISSUE THREAD

**Issue by GabrielAlves0501** [GabrielAlves0501/GCMS-Gabriel-Alves#1]
@ramidedantas, solicita para entrar como colaborador.

[README](https://github.com/GabrielAlves0501/GCMS-Gabriel-Alves/edit/main/README.md)

**Comment by ramidedantas** [comment]
@GabrielAlves0501 nome adicionado, pode fechar o chamado

**Comment by GabrielAlves0501** [comment]
Fechando chamado!
